### ISSUE TITLE
Infinite wait for response on 2013.05 Rakudo Star RC

### ISSUE THREAD

**Issue by bbkr** [supernovus/perl6-http-easy#12]
Details are described in Star https://github.com/rakudo/star/issues/22

Tested on http://pmichaud.com/sandbox/rakudo-star-2013.05-rc1.tar.gz

**Comment by azawawi** [comment]
Is this still valid?

**Comment by supernovus** [comment]
No, it was resolved on May 30, 2013.

**Comment by azawawi** [comment]
Thanks :+1:
