### ISSUE TITLE
Use of uninitialized value of type Any in numeric context

### ISSUE THREAD

**Issue by slidaway** [supernovus/perl6-http-easy#32]
Use of uninitialized value of type Any in numeric context
  in block  at /root/.rakudobrew/moar-nom/install/share/perl6/site/sources/100A1B43D02574570A9FA5
343A0679EF35FBD229 (HTTP::Easy) line 101
Will not decode invalid ASCII (code point > 127 found)
  in method run at /root/.rakudobrew/moar-nom/install/share/perl6/site/sources/100A1B43D02574570A
9FA5343A0679EF35FBD229 (HTTP::Easy) line 103
  in sub baile at /root/.rakudobrew/moar-nom/install/share/perl6/site/sources/D57520A5A045A33D405
E36DAA759641E90C1FD99 (Bailador) line 95
  in block <unit> at app.pm6 line 30

**Comment by benjif** [comment]
oh jeez, I've posted this on the wrong github page

**Comment by supernovus** [comment]
If it's a bug in HTTP::Easy, this would be the right page. If it's a bug in Bailador, then it wouldn't be. I haven't had a chance to look at the code in question though, so not sure which.
